[pytest]
testpaths = tests/automated
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    regressao: Testes de regressão
    funcional: Testes funcionais
    critical: Testes críticos
    slow: Testes lentos
addopts = -v --strict-markers